#!/usr/bin/perl -n

# usage

# hc2html < input > output
# hc2html input1 input2 .... inputn > output

# converts a file from MacOS 9 (sic!) character set to HTMl entities and 7 bit

s/Ä/\&Auml;/go;
s/Å/\&Aring;/go;
s/Ç/\&Ccedil;/go;
s/É/\&Eacute;/go;
s/Ñ/\&Ntilde;/go;
s/Ö/\&Ouml;/go;
s/Ü/\&Uuml;/go;
s/á/\&aacute;/go;
s/à/\&agrave;/go;
s/â/\&acirc;/go;
s/ä/\&auml;/go;
s/ã/\&atilde;/go;
s/å/\&aring;/go;
s/ç/\&ccedil;/go;
s/é/\&eacute;/go;
s/è/\&egrave;/go;
s/ê/\&ecirc;/go;
s/ë/\&euml;/go;
s/í/\&iacute;/go;
s/ì/\&igrave;/go;
s/î/\&icirc;/go;
s/ï/\&iuml;/go;
s/ñ/\&ntilde;/go;
s/ó/\&oacute;/go;
s/ò/\&ograve;/go;
s/ô/\&ocirc;/go;
s/ö/\&ouml;/go;
s/õ/\&otilde;/go;
s/ú/\&uacute;/go;
s/ù/\&ugrave;/go;
s/û/\&ucirc;/go;
s/ü/\&uuml;/go;
s/°/\&deg;/go;
s/¢/\&cent;/go;
s/£/\&pound;/go;
s/§/\&sect;/go;
s/¶/\&para;/go;
s/ß/\&szlig;/go;
s/®/\&reg;/go;
s/©/\&copy;/go;
s/´/\&acute;/go;
s/¨/\&uml;/go;
s/Æ/\&AElig;/go;
s/Ø/\&Oslash;/go;
s/±/\&plusmn;/go;
s/¥/\&yen;/go;
s/µ/\&micro;/go;
s/ª/\&ordf;/go;
s/º/\&ordm;/go;
s/æ/\&aelig;/go;
s/ø/\&oslash;/go;
s/¿/\&iquest;/go;
s/¡/\&iexcl;/go;
s/¬/\&not;/go;
s/«/\&laquo;/go;
s/»/\&raquo;/go;
s/ /\&nbsp;/go;
s/À/\&Agrave;/go;
s/Ã/\&Atilde;/go;
s/Õ/\&Otilde;/go;
s/÷/\&divide;/go;
s/ÿ/\&yuml;/go;
s/€/\&curren;/go;
s/·/\&middot;/go;
s/Â/\&Acirc;/go;
s/Ê/\&Ecirc;/go;
s/Á/\&Aacute;/go;
s/Ë/\&Euml;/go;
s/È/\&Egrave;/go;
s/Í/\&Iacute;/go;
s/Î/\&Icirc;/go;
s/Ï/\&Iuml;/go;
s/Ì/\&Igrave;/go;
s/Ó/\&Oacute;/go;
s/Ô/\&Ocirc;/go;
s/Ò/\&Ograve;/go;
s/Ú/\&Uacute;/go;
s/Û/\&Ucirc;/go;
s/Ù/\&Ugrave;/go;
s/¯/\&hibar;/go;
s/¸/\&cedil;/go;
print $_;
