#!/usr/bin/perl -n

# usage

# html2dcr < input > output
# html2dcr input1 input2 .... inputn > output

# converts a file from HTML-entities to the TeX-dcr character set

s/\&sect;/Ÿ/go;
s/\&yuml;/¸/go;
s/\&iexcl;/½/go;
s/\&iquest;/¾/go;
s/\&pound;/¿/go;
s/\&Agrave;/À/go;
s/\&Aacute;/Á/go;
s/\&Acirc;/Â/go;
s/\&Atilde;/Ã/go;
s/\&Auml;/Ä/go;
s/\&Aring;/Å/go;
s/\&AElig;/Æ/go;
s/\&Ccedil;/Ç/go;
s/\&Egrave;/È/go;
s/\&Eacute;/É/go;
s/\&Ecirc;/Ê/go;
s/\&Euml;/Ë/go;
s/\&Igrave;/Ì/go;
s/\&Iacute;/Í/go;
s/\&Icirc;/Î/go;
s/\&Iuml;/Ï/go;
s/\&ETH;/Ð/go;
s/\&Ntilde;/Ñ/go;
s/\&Ograve;/Ò/go;
s/\&Oacute;/Ó/go;
s/\&Ocirc;/Ô/go;
s/\&Otilde;/Õ/go;
s/\&Ouml;/Ö/go;
s/\&Oslash;/Ø/go;
s/\&Ugrave;/Ù/go;
s/\&Uacute;/Ú/go;
s/\&Ucirc;/Û/go;
s/\&Uuml;/Ü/go;
s/\&Yacute;/Ý/go;
s/\&THORN;/Þ/go;
s/\&agrave;/à/go;
s/\&aacute;/á/go;
s/\&acirc;/â/go;
s/\&atilde;/ã/go;
s/\&auml;/ä/go;
s/\&aring;/å/go;
s/\&aelig;/æ/go;
s/\&ccedil;/ç/go;
s/\&egrave;/è/go;
s/\&eacute;/é/go;
s/\&ecirc;/ê/go;
s/\&euml;/ë/go;
s/\&igrave;/ì/go;
s/\&iacute;/í/go;
s/\&icirc;/î/go;
s/\&iuml;/ï/go;
s/\&eth;/ð/go;
s/\&ntilde;/ñ/go;
s/\&ograve;/ò/go;
s/\&oacute;/ó/go;
s/\&ocirc;/ô/go;
s/\&otilde;/õ/go;
s/\&ouml;/ö/go;
s/\&oslash;/ø/go;
s/\&ugrave;/ù/go;
s/\&uacute;/ú/go;
s/\&ucirc;/û/go;
s/\&uuml;/ü/go;
s/\&yacute;/ý/go;
s/\&thorn;/þ/go;
s/\&szlig;/ÿ/go;
print $_;
