#!/usr/bin/perl -n

# usage

# html2atari < input > output
# html2atari input1 input2 .... inputn > output

# converts a file from HTML-entities to the Atari ST character set

s/\&Ccedil;/Ä/go;
s/\&uuml;/Å/go;
s/\&eacute;/Ç/go;
s/\&acirc;/É/go;
s/\&auml;/Ñ/go;
s/\&agrave;/Ö/go;
s/\&aring;/Ü/go;
s/\&ccedil;/á/go;
s/\&ecirc;/à/go;
s/\&euml;/â/go;
s/\&egrave;/ä/go;
s/\&iuml;/ã/go;
s/\&icirc;/å/go;
s/\&igrave;/ç/go;
s/\&Auml;/é/go;
s/\&Aring;/è/go;
s/\&Eacute;/ê/go;
s/\&aelig;/ë/go;
s/\&AElig;/í/go;
s/\&ocirc;/ì/go;
s/\&ouml;/î/go;
s/\&ograve;/ï/go;
s/\&ucirc;/ñ/go;
s/\&ugrave;/ó/go;
s/\&yuml;/ò/go;
s/\&Ouml;/ô/go;
s/\&Uuml;/ö/go;
s/\&cent;/õ/go;
s/\&pound;/ú/go;
s/\&yen;/ù/go;
s/\&szlig;/û/go;
s/\&aacute;/†/go;
s/\&iacute;/°/go;
s/\&oacute;/¢/go;
s/\&uacute;/£/go;
s/\&ntilde;/§/go;
s/\&Ntilde;/•/go;
s/\&ordf;/¶/go;
s/\&ordm;/ß/go;
s/\&iquest;/®/go;
s/\&not;/™/go;
s/\&frac12;/´/go;
s/\&frac14;/¨/go;
s/\&iexcl;/≠/go;
s/\&laquo;/Æ/go;
s/\&raquo;/Ø/go;
s/\&atilde;/∞/go;
s/\&otilde;/±/go;
s/\&Oslash;/≤/go;
s/\&oslash;/≥/go;
s/\&Agrave;/∂/go;
s/\&Atilde;/∑/go;
s/\&Otilde;/∏/go;
s/\&uml;/π/go;
s/\&acute;/∫/go;
s/\&para;/º/go;
s/\&copy;/Ω/go;
s/\&reg;/æ/go;
s/\&sect;/›/go;
s/\&micro;/Ê/go;
s/\&plusmn;/Ò/go;
s/\&divide;/ˆ/go;
s/\&deg;/¯/go;
s/\&middot;/˙/go;
s/\&sup2;/˝/go;
s/\&sup3;/˛/go;
s/\&hibar;/ˇ/go;
print $_;
