#!/usr/bin/perl -n

# usage

# html2din < input > output
# html2din input1 input2 .... inputn > output

# converts a file from HTML-entities to iso646.de

s/\&sect;/@/go;
s/\&Auml;/[/go;
s/\&Ouml;/\/go;
s/\&Uuml;/]/go;
s/\&auml;/{/go;
s/\&ouml;/|/go;
s/\&uuml;/}/go;
s/\&szlig;/~/go;
print $_;
