#!/usr/bin/perl -n

# usage

# html2hc < input > output
# html2hc input1 input2 .... inputn > output

# converts a file from HTML-entities to the Apple MacOS 9 (sic!) charset

s/\&Auml;/Ä/go;
s/\&Aring;/Å/go;
s/\&Ccedil;/Ç/go;
s/\&Eacute;/É/go;
s/\&Ntilde;/Ñ/go;
s/\&Ouml;/Ö/go;
s/\&Uuml;/Ü/go;
s/\&aacute;/á/go;
s/\&agrave;/à/go;
s/\&acirc;/â/go;
s/\&auml;/ä/go;
s/\&atilde;/ã/go;
s/\&aring;/å/go;
s/\&ccedil;/ç/go;
s/\&eacute;/é/go;
s/\&egrave;/è/go;
s/\&ecirc;/ê/go;
s/\&euml;/ë/go;
s/\&iacute;/í/go;
s/\&igrave;/ì/go;
s/\&icirc;/î/go;
s/\&iuml;/ï/go;
s/\&ntilde;/ñ/go;
s/\&oacute;/ó/go;
s/\&ograve;/ò/go;
s/\&ocirc;/ô/go;
s/\&ouml;/ö/go;
s/\&otilde;/õ/go;
s/\&uacute;/ú/go;
s/\&ugrave;/ù/go;
s/\&ucirc;/û/go;
s/\&uuml;/ü/go;
s/\&deg;/°/go;
s/\&cent;/¢/go;
s/\&pound;/£/go;
s/\&sect;/§/go;
s/\&para;/¶/go;
s/\&szlig;/ß/go;
s/\&reg;/®/go;
s/\&copy;/©/go;
s/\&acute;/´/go;
s/\&uml;/¨/go;
s/\&AElig;/Æ/go;
s/\&Oslash;/Ø/go;
s/\&plusmn;/±/go;
s/\&yen;/¥/go;
s/\&micro;/µ/go;
s/\&ordf;/ª/go;
s/\&ordm;/º/go;
s/\&aelig;/æ/go;
s/\&oslash;/ø/go;
s/\&iquest;/¿/go;
s/\&iexcl;/¡/go;
s/\&not;/¬/go;
s/\&laquo;/«/go;
s/\&raquo;/»/go;
s/\&nbsp;/ /go;
s/\&Agrave;/À/go;
s/\&Atilde;/Ã/go;
s/\&Otilde;/Õ/go;
s/\&divide;/÷/go;
s/\&yuml;/ÿ/go;
s/\&curren;/€/go;
s/\&middot;/·/go;
s/\&Acirc;/Â/go;
s/\&Ecirc;/Ê/go;
s/\&Aacute;/Á/go;
s/\&Euml;/Ë/go;
s/\&Egrave;/È/go;
s/\&Iacute;/Í/go;
s/\&Icirc;/Î/go;
s/\&Iuml;/Ï/go;
s/\&Igrave;/Ì/go;
s/\&Oacute;/Ó/go;
s/\&Ocirc;/Ô/go;
s/\&Ograve;/Ò/go;
s/\&Uacute;/Ú/go;
s/\&Ucirc;/Û/go;
s/\&Ugrave;/Ù/go;
s/\&hibar;/¯/go;
s/\&cedil;/¸/go;
print $_;
